"use client";

import { FormEvent, useCallback, useEffect, useState } from "react";
import { Add, CheckCircleOutline, GroupOutlined, LayersOutlined, PaidOutlined, PersonAddAltOutlined, Search } from "@mui/icons-material";
import { DashboardStat } from "./components/dashboard-stat";
import { ExpenseGroupCard } from "./components/expense-group-card";
import { PersonBalanceCard } from "./components/person-balance-card";
import type { DebtItem, ExpenseGroup, Person } from "./components/dashboard-types";
import { ApiError, type ApiGroup, type ApiPerson, debtApi } from "./components/debt-api";

const money = (value: number) => `฿${value.toLocaleString("th-TH")}`;
type ModalType = "person" | "group" | "payment" | null;

export default function Home() {
  const [people, setPeople] = useState<Person[]>([]);
  const [groups, setGroups] = useState<ExpenseGroup[]>([]);
  const [search, setSearch] = useState("");
  const [filter, setFilter] = useState<"all" | "open" | "paid">("all");
  const [selectedGroupId, setSelectedGroupId] = useState<string | null>(null);
  const [favoriteIds, setFavoriteIds] = useState<string[]>([]);
  const [token, setToken] = useState<string | null>(null);
  const [loading, setLoading] = useState(true);
  const [message, setMessage] = useState("");
  const [authMode, setAuthMode] = useState<"login" | "register">("login");
  const [modal, setModal] = useState<ModalType>(null);
  const [paymentPerson, setPaymentPerson] = useState<Person | null>(null);
  const [pendingAction, setPendingAction] = useState<string | null>(null);

  const mapDashboardData = useCallback((apiPeople: ApiPerson[], apiGroups: ApiGroup[]) => {
    const totals = new Map<string, { amount: number; bills: number; debts: DebtItem[] }>();
    for (const group of apiGroups) for (const bill of group.bills.filter((item) => item.paymentStatus === "PENDING")) {
      const current = totals.get(bill.personId) ?? { amount: 0, bills: 0, debts: [] };
      current.amount += bill.amount; current.bills += 1;
      current.debts.push({ id: bill.id, amount: bill.amount, description: bill.description, groupId: group.id, groupName: group.name, createdAt: bill.createdAt });
      totals.set(bill.personId, current);
    }
    setPeople(apiPeople.map((person) => {
      const groupTotal = totals.get(person.id) ?? { amount: 0, bills: 0, debts: [] };
      const directDebts = (person.personalBills ?? []).map((bill) => ({ id: bill.id, amount: bill.amount, description: bill.description, createdAt: bill.createdAt }));
      const amount = groupTotal.amount + (person.personalTotalOwed ?? 0);
      return { id: person.id, name: person.name, nickname: person.name.split(/\s+/)[0] || person.name, phone: "ไม่ได้ระบุ", amount, bills: groupTotal.bills + (person.personalBillCount ?? 0), paid: amount <= 0, debts: [...groupTotal.debts, ...directDebts] };
    }));
    setGroups(apiGroups.map((group) => ({ id: group.id, title: group.name, category: "กลุ่มหารเงิน", date: new Intl.DateTimeFormat("th-TH", { dateStyle: "medium" }).format(new Date(group.createdAt)), total: group.totalOwed, people: group.members.map((member) => member.person.id), lastAmount: group.charges.at(-1) ? group.charges.at(-1)!.amountPerPerson * group.members.length : undefined, favorite: favoriteIds.includes(group.id), memberOwed: Object.fromEntries(group.members.map((member) => [member.person.id, member.totalOwed])) })));
  }, [favoriteIds]);

  const loadData = useCallback(async (accessToken: string) => {
    setLoading(true);
    try { const [apiPeople, apiGroups] = await Promise.all([debtApi.people(accessToken), debtApi.groups(accessToken)]); mapDashboardData(apiPeople, apiGroups); }
    catch (error) { const text = error instanceof ApiError ? error.message : "Unable to reach the data service."; setMessage(text); if (error instanceof ApiError && error.status === 401) { localStorage.removeItem("plodnhee-access-token"); setToken(null); } }
    finally { setLoading(false); }
  }, [mapDashboardData]);

  useEffect(() => { setFavoriteIds(JSON.parse(localStorage.getItem("plodnhee-favorite-groups") ?? "[]")); const saved = localStorage.getItem("plodnhee-access-token"); if (saved) setToken(saved); else setLoading(false); }, []);
  useEffect(() => { if (token) void loadData(token); }, [loadData, token]);
  useEffect(() => { localStorage.setItem("plodnhee-favorite-groups", JSON.stringify(favoriteIds)); }, [favoriteIds]);

  const outstanding = people.filter((person) => !person.paid).reduce((sum, person) => sum + person.amount, 0);
  const visiblePeople = people.filter((person) => `${person.name} ${person.nickname}`.toLowerCase().includes(search.toLowerCase()) && (filter === "all" || (filter === "paid" ? person.paid : !person.paid)));
  const quickGroups = [...groups].filter((group) => group.lastAmount).sort((a, b) => Number(Boolean(b.favorite)) - Number(Boolean(a.favorite)));

  async function authenticate(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form = new FormData(event.currentTarget); setPendingAction("auth"); try { const session = authMode === "login" ? await debtApi.login(String(form.get("email")), String(form.get("password"))) : await debtApi.register(String(form.get("email")), String(form.get("password"))); localStorage.setItem("plodnhee-access-token", session.accessToken); setToken(session.accessToken); setMessage(""); } catch (error) { setMessage(error instanceof Error ? error.message : "Unable to sign in."); } finally { setPendingAction(null); } }
  async function addPerson(form: FormData) { if (!token) return; const name = String(form.get("name") || "").trim(); if (!name) return; setPendingAction("person"); try { await debtApi.createPerson(token, name); setModal(null); await loadData(token); } catch (error) { setMessage(error instanceof Error ? error.message : "Unable to add person."); } finally { setPendingAction(null); } }
  async function createGroup(event: FormEvent<HTMLFormElement>) { event.preventDefault(); if (!token) return; const form = new FormData(event.currentTarget); const name = String(form.get("name") || "").trim(); const memberIds = form.getAll("memberIds").map(String); if (!name || !memberIds.length) { setMessage("กรุณาตั้งชื่อกรุ๊ปและเลือกสมาชิกอย่างน้อย 1 คน"); return; } setPendingAction("group"); try { await debtApi.createGroup(token, name, memberIds); setModal(null); await loadData(token); } catch (error) { setMessage(error instanceof Error ? error.message : "Unable to create group."); } finally { setPendingAction(null); } }
  async function addCharge(group: ExpenseGroup, amount: number) { if (!token || !Number.isFinite(amount) || amount <= 0) return; setPendingAction(`charge:${group.id}`); try { await debtApi.createCharge(token, group.id, amount); await loadData(token); setMessage(`เพิ่มยอดรวม ${money(amount)} แล้ว`); } catch (error) { setMessage(error instanceof Error ? error.message : "Unable to add charge."); } finally { setPendingAction(null); } }
  async function addPersonalDebt(event: FormEvent<HTMLFormElement>) { event.preventDefault(); if (!token || !paymentPerson) return; const form = new FormData(event.currentTarget); const amount = Number(form.get("amount")); setPendingAction("personal-debt"); try { await debtApi.createPersonalBill(token, paymentPerson.id, amount, String(form.get("description") || "").trim() || undefined); await loadData(token); setMessage("เพิ่มยอดรายคนแล้ว"); } catch (error) { setMessage(error instanceof Error ? error.message : "Unable to add debt."); } finally { setPendingAction(null); } }
  async function pay(debt?: DebtItem) { if (!token || !paymentPerson) return; setPendingAction(debt ? `pay:${debt.id}` : "pay:all"); try { if (debt?.groupId) await debtApi.payGroupBills(token, debt.groupId, paymentPerson.id, "one", debt.id); else if (debt) await debtApi.payPersonalBills(token, paymentPerson.id, "one", debt.id); else { const groupIds = [...new Set(paymentPerson.debts.map((item) => item.groupId).filter(Boolean))] as string[]; await Promise.all([debtApi.payPersonalBills(token, paymentPerson.id, "all").catch(() => undefined), ...groupIds.map((groupId) => debtApi.payGroupBills(token, groupId, paymentPerson.id, "all").catch(() => undefined))]); } await loadData(token); setMessage(debt ? "เคลียร์บิลที่เลือกแล้ว" : "เคลียร์หนี้ทั้งหมดแล้ว"); } catch (error) { setMessage(error instanceof Error ? error.message : "Unable to record payment."); } finally { setPendingAction(null); } }

  if (!token) return <main className="mx-auto grid min-h-screen max-w-md place-items-center p-5"><form className="grid w-full gap-4 rounded-[20px] border border-[#e2e8f1] bg-white p-7 shadow-[0_3px_5px_#1929500b]" onSubmit={authenticate}><div><h1 className="m-0 text-2xl font-bold">Plodnhee</h1><p className="mt-1 text-[#75839a]">{authMode === "login" ? "เข้าสู่ระบบเพื่อดูข้อมูลจริงของคุณ" : "สร้างบัญชีเพื่อเริ่มจัดการยอดหารเงิน"}</p></div><input className="rounded-[10px] border border-[#e2e8f1] p-3" name="email" type="email" placeholder="อีเมล" required disabled={pendingAction === "auth"} /><input className="rounded-[10px] border border-[#e2e8f1] p-3" name="password" type="password" minLength={8} placeholder="รหัสผ่าน (อย่างน้อย 8 ตัว)" required disabled={pendingAction === "auth"} />{message && <p className="m-0 text-sm font-semibold text-[#d9344e]">{message}</p>}<button className="inline-flex items-center justify-center gap-2 rounded-[13px] bg-[#3863df] px-[22px] py-[13px] font-bold text-white" disabled={pendingAction === "auth"}>{pendingAction === "auth" && <span className="button-spinner" />}{pendingAction === "auth" ? "กำลังดำเนินการ..." : authMode === "login" ? "เข้าสู่ระบบ" : "สร้างบัญชี"}</button><button className="text-sm font-bold text-[#3863df]" type="button" disabled={pendingAction === "auth"} onClick={() => setAuthMode((mode) => mode === "login" ? "register" : "login")}>{authMode === "login" ? "ยังไม่มีบัญชี? สร้างบัญชี" : "มีบัญชีแล้ว? เข้าสู่ระบบ"}</button></form></main>;

  return <main className="mx-auto max-w-[1820px] px-4 pb-20 pt-4 md:px-6 md:pt-9 xl:px-12">
    <div className="mb-3 flex justify-end"><button className="text-sm font-bold text-[#75839a] hover:text-[#3863df]" disabled={pendingAction !== null} onClick={() => { localStorage.removeItem("plodnhee-access-token"); setToken(null); }}>ออกจากระบบ / เปลี่ยนบัญชี</button></div>
    <section className="grid grid-cols-1 gap-4 sm:grid-cols-2 xl:grid-cols-4 xl:gap-[26px]"><DashboardStat label="ยอดค้างชำระรวม" value={money(outstanding)} hint="ที่ยังเก็บเงินไม่ครบ" color="red" icon={<PaidOutlined />} /><DashboardStat label="จ่ายครบแล้ว" value={`${people.filter((person) => person.paid).length} คน`} hint="ไม่มีบิลค้าง" color="green" icon={<CheckCircleOutline />} /><DashboardStat label="ลูกหนี้ค้างชำระ" value={`${people.filter((person) => !person.paid).length} คน`} hint={`จากทั้งหมด ${people.length} คน`} color="orange" icon={<GroupOutlined />} /><DashboardStat label="จำนวนกรุ๊ป/ทริป" value={`${groups.length} กรุ๊ป`} hint="รายการหารเงินทั้งหมด" color="blue" icon={<LayersOutlined />} /></section>
    <section className="mt-7 grid items-start gap-7 xl:mt-[42px] xl:grid-cols-[minmax(0,1.42fr)_minmax(460px,1fr)] xl:gap-[38px]"><div><header className="mb-6 flex flex-col items-start justify-between gap-4 sm:flex-row"><div><h1 className="m-0 text-[23px] font-bold md:text-[27px]"><PaidOutlined className="mr-3 align-[-5px] text-[32px] text-[#4f83ef]" />รายการกรุ๊ปหารเงิน</h1><p className="m-0 mt-0.5 text-base font-medium text-[#8491a7]">สร้างกรุ๊ป เพิ่มยอดเดิมซ้ำ หรือเพิ่มยอดให้คนเดียว</p></div><button className="inline-flex items-center gap-2 rounded-[13px] bg-[#3863df] px-[22px] py-[13px] font-bold text-white" disabled={pendingAction !== null} onClick={() => setModal("group")}><Add /> สร้างกรุ๊ปหารเงิน</button></header>
      {!!quickGroups.length && <div className="mb-5 rounded-2xl border border-[#e2e8f1] bg-[#f7f9ff] p-4"><b>เพิ่มยอดเดิมอย่างรวดเร็ว</b><div className="mt-2 flex flex-wrap gap-2">{quickGroups.map((group) => <button key={group.id} className="rounded-full border border-[#cddbf5] bg-white px-3 py-1.5 text-sm font-bold text-[#3863df]" onClick={() => setSelectedGroupId(group.id)}>{group.favorite ? "★ " : ""}{group.title} · รวม {money(group.lastAmount!)}</button>)}</div><small className="mt-2 block text-[#71809a]">เลือกกรุ๊ปแล้วกดเพิ่มยอด ระบบจะใช้ราคารวมครั้งล่าสุดให้</small></div>}
      <div className="grid gap-[18px]">{loading ? <p className="p-8 text-center text-[#8491a7]">กำลังโหลดข้อมูลจริง…</p> : groups.map((group) => <ExpenseGroupCard key={group.id} group={group} people={people} selected={selectedGroupId === group.id} onSelect={() => setSelectedGroupId(selectedGroupId === group.id ? null : group.id)} onAddCharge={addCharge} onToggleFavorite={() => setFavoriteIds((ids) => ids.includes(group.id) ? ids.filter((id) => id !== group.id) : [...ids, group.id])} isAddingCharge={pendingAction === `charge:${group.id}`} />)}</div>
    </div><aside><header className="mb-6 flex flex-col items-start justify-between gap-4 sm:flex-row"><div><h2 className="m-0 text-[23px] font-bold md:text-[26px]"><GroupOutlined className="mr-3 align-[-5px] text-[32px] text-[#4f83ef]" />สรุปยอดแยกตามบุคคล</h2><p className="m-0 mt-0.5 text-base font-medium text-[#8491a7]">เลือกจ่ายบิลเดียว หรือเคลียร์ทุกบิลที่ค้าง</p></div><button className="inline-flex items-center gap-2 rounded-[13px] border border-[#e2e8f1] bg-[#f9fbff] px-[22px] py-[13px] font-bold text-[#526178]" disabled={pendingAction !== null} onClick={() => setModal("person")}><PersonAddAltOutlined /> เพิ่มลูกหนี้</button></header><div className="mb-[26px] rounded-[20px] border border-[#e2e8f1] bg-white p-5"><label className="flex h-11 items-center gap-2.5 rounded-full bg-[#f1f4f8] px-[17px] text-[#8fa0b8]"><Search /><input className="min-w-0 flex-1 border-0 bg-transparent font-semibold text-[#172239] outline-none" value={search} onChange={(event) => setSearch(event.target.value)} placeholder="ค้นหาชื่อ หรือชื่อเล่น..." /></label><div className="mt-[18px] flex rounded-[25px] bg-[#f1f4f8] p-1">{[["all", `ทั้งหมด (${people.length})`], ["open", "ยังค้างอยู่"], ["paid", "จ่ายครบแล้ว"]].map(([value, label]) => <button key={value} className={`flex-1 rounded-[17px] px-1 py-2 text-xs font-bold md:text-base ${filter === value ? "bg-[#3863df] text-white" : "text-[#6c7a91]"}`} disabled={pendingAction !== null} onClick={() => setFilter(value as typeof filter)}>{label}</button>)}</div></div><div className="grid gap-[18px]">{visiblePeople.map((person) => <PersonBalanceCard key={person.id} person={person} onPay={(selected) => { setPaymentPerson(selected); setModal("payment"); }} onDelete={() => setMessage("ยังไม่รองรับการลบเพื่อป้องกันประวัติหนี้สูญหาย")} />)}</div></aside></section>
    {message && <p className="fixed bottom-5 right-5 z-30 max-w-sm rounded-xl bg-[#172239] px-4 py-3 font-semibold text-white shadow-lg">{message}</p>}
    {modal === "person" && <Modal onClose={() => !pendingAction && setModal(null)}><form className="grid gap-3.5" action={addPerson}><h2 className="text-2xl font-bold">เพิ่มลูกหนี้</h2><input className="rounded-[10px] border p-3" name="name" placeholder="ชื่อ - นามสกุล" required disabled={pendingAction === "person"} /><ModalActions busy={pendingAction === "person"} /></form></Modal>}
    {modal === "group" && <Modal onClose={() => !pendingAction && setModal(null)}><form className="grid gap-3.5" onSubmit={createGroup}><h2 className="text-2xl font-bold">สร้างกรุ๊ปหารเงิน</h2><input className="rounded-[10px] border p-3" name="name" placeholder="เช่น ค่าอาหารประจำเดือน" required disabled={pendingAction === "group"} /><b>เลือกสมาชิก</b><div className="grid max-h-52 gap-2 overflow-y-auto">{people.map((person) => <label key={person.id} className="flex items-center gap-2 rounded-lg bg-[#f5f7fb] p-2"><input type="checkbox" name="memberIds" value={person.id} disabled={pendingAction === "group"} /> {person.name}</label>)}</div><ModalActions busy={pendingAction === "group"} /></form></Modal>}
    {modal === "payment" && paymentPerson && <Modal onClose={() => !pendingAction && setModal(null)}><div className="grid gap-4"><div><h2 className="text-2xl font-bold">{paymentPerson.name}</h2><p className="text-[#75839a]">ค้างทั้งหมด {money(paymentPerson.amount)} · {paymentPerson.bills} บิล</p></div><button className="inline-flex items-center justify-center gap-2 rounded-[13px] bg-[#198754] px-4 py-3 font-bold text-white" disabled={pendingAction !== null} onClick={() => void pay()}>{pendingAction === "pay:all" && <span className="button-spinner" />}{pendingAction === "pay:all" ? "กำลังเคลียร์..." : "เคลียร์หนี้ทั้งหมด"}</button><div className="grid gap-2">{paymentPerson.debts.map((debt) => <div key={debt.id} className="flex items-center justify-between gap-3 rounded-xl border p-3"><div><b>{debt.groupName ?? "ยอดรายคน"} · {money(debt.amount)}</b><small className="block text-[#75839a]">{debt.description || "ไม่มีรายละเอียด"}</small></div><button className="inline-flex items-center gap-2 rounded-lg border border-[#3863df] px-3 py-2 font-bold text-[#3863df]" disabled={pendingAction !== null} onClick={() => void pay(debt)}>{pendingAction === `pay:${debt.id}` && <span className="button-spinner" />}{pendingAction === `pay:${debt.id}` ? "กำลังชำระ..." : "จ่ายบิลนี้"}</button></div>)}</div><form className="grid gap-2 border-t pt-4" onSubmit={addPersonalDebt}><b>เพิ่มยอดให้คนนี้โดยไม่ต้องสร้างกรุ๊ป</b><input className="rounded-[10px] border p-3" name="amount" type="number" min="1" step="0.01" placeholder="จำนวนเงิน" required disabled={pendingAction === "personal-debt"} /><input className="rounded-[10px] border p-3" name="description" placeholder="รายละเอียด (ไม่บังคับ)" disabled={pendingAction === "personal-debt"} /><button className="inline-flex items-center justify-center gap-2 rounded-[13px] bg-[#3863df] px-4 py-3 font-bold text-white" disabled={pendingAction !== null}>{pendingAction === "personal-debt" && <span className="button-spinner" />}{pendingAction === "personal-debt" ? "กำลังเพิ่ม..." : "เพิ่มยอดรายคน"}</button></form></div></Modal>}
  </main>;
}

function Modal({ children, onClose }: { children: React.ReactNode; onClose: () => void }) { return <div className="fixed inset-0 z-20 grid place-items-center bg-[#0e1a2c66] p-5" onClick={onClose}><div className="w-full max-w-[500px] rounded-[20px] bg-white p-7" onClick={(event) => event.stopPropagation()}>{children}</div></div>; }
function ModalActions({ busy }: { busy: boolean }) { return <div className="mt-2 flex justify-end"><button className="inline-flex items-center gap-2 rounded-[13px] bg-[#3863df] px-[22px] py-[13px] font-bold text-white" disabled={busy}>{busy && <span className="button-spinner" />}{busy ? "กำลังบันทึก..." : "บันทึก"}</button></div>; }
